default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tokudayuuta
  password: tokudayuuta
  timeout: 5000

development:
  <<: *default
  database: book_memo_development

production:
  <<: *default
  database: book_memo_pro